version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "pswgcommon"
    schedule:
      interval: "weekly"
      day: "saturday"
