CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	password TEXT NOT NULL,
	email TEXT NOT NULL,
	access_level TEXT NOT NULL,
	banned INTEGER NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS players (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	race TEXT NOT NULL,
	userid INTEGER NOT NULL
);
