name: Lint

on:
  pull_request:
  push:
    branches: 
    - master

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: run ktlint
        run: |
          ./gradlew --no-daemon ktlintCheck
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v3
        with:
          report-path: build/reports/ktlint/*/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-ktlint exit 1.
